packages:
  - packages/**

# 重複排除
dedupePeers: true

catalog:
  date-fns: 4.4.0
  react: &react_ver 19.2.7
  react-dom: *react_ver
  rolldown: 1.2.4
  rolldown-plugin-dts: 0.28.2
  turbo: 2.10.9
  typescript: 7.0.2
  vite: 8.2.1
  vitest: &vitest_ver 4.1.10
  '@biomejs/biome': 2.5.8
  '@date-fns/tz': 1.5.0
  '@fast-check/vitest': 0.4.1
  '@fullcalendar/core': &fullcalendar_ver 6.1.21
  '@fullcalendar/daygrid': *fullcalendar_ver
  '@fullcalendar/interaction': *fullcalendar_ver
  '@fullcalendar/react': *fullcalendar_ver
  '@fullcalendar/timegrid': *fullcalendar_ver
  '@types/node': 26.2.0
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.4
  '@vitejs/plugin-react': 6.0.5
  '@vitest/coverage-v8': *vitest_ver
  '@vitest/expect': *vitest_ver
  '@vitest/mocker': *vitest_ver
  '@vitest/spy': *vitest_ver

overrides:
  # CVE-2026-67213
  nanoid: ^3.3.17
  rolldown: 'catalog:'
  '@vitest/expect': 'catalog:'
  '@vitest/mocker': 'catalog:'
  '@vitest/spy': 'catalog:'

# リリースから一定時間経過していないか、信頼性低下したパッケージはインストールしない
minimumReleaseAge: 2880 # 2d
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade

# 特殊なソースからの依存関係をインストールしない
blockExoticSubdeps: true
